import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/34cf304f66.js" crossOrigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossOrigin="anonymous" />
        <link rel="stylesheet" href="../styles/Home.module.css" />
      </Head>

      <nav className="navbar bg-light">
        <div className="container-fluid">
          <Image src="/logouleam.png" width={200} height={80} className="navbar-brand" />
          <div className="btn p-3 fs-3"> Inicio </div>
        </div>
      </nav>

      <div className={styles.complete}>
        <div className="container text-center bg-secondary p-5">
          <div className="row">
            <div className="col m-50 bg-white" >
              <Link href="/estudiante">
              <a>
                Estudiante
                <div>
                  <Image src="/estudiante.png" width={300} height={300}></Image>
                </div>
              </a>
              </Link>
            </div>
            <div className="col m-50 bg-white ms-5">
              <a href="">
                Docente
                <div>
                  <Image src="/docente.png" width={300} height={300}></Image>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>





      <footer className='bg-dark text-white pt-5 pb-4'>
        <div className="container text-center text-md-left">
          <div className='row text-center text-md-left'>
            <div className='col-md-5 col-lg-5 col-xl-5 mx-auto mt-2'>
              <h5 className="text-uppercase mb-3 font-weight-bold text-warning">ULEAM @ Copyright 2022, Todos los derechos reservados - Universidad Laica Eloy Alfaro de Manabí</h5>
              <p className='text-while'>Dirección: Av. Circunvalación - Vía a San Mateo</p>
              <p className='text-while'>Manta - Manabí - Ecuador</p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

export default Home
